### ISSUE TITLE
Support SVG element-specific CSS properties

### ISSUE THREAD

**Issue by jcready** [frenic/csstype#69]
See https://www.w3.org/TR/SVG2/styling.html and https://css-tricks.com/svg-properties-and-css/

For example:

```css
circle {
  r: 5
}
```
